apiVersion: v1
kind: Namespace
metadata:
  name: defensys
  labels:
    name: defensys
    app: defensys-scanner
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: defensys-quota
  namespace: defensys
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defensys-limits
  namespace: defensys
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
